// Code generated by MockGen. DO NOT EDIT.
// Source: ../aerospace-ipc/pkg/aerospace/windows/windows.go
//
// Generated by this command:
//
//	mockgen -source=../aerospace-ipc/pkg/aerospace/windows/windows.go -destination=internal/mocks/windows/windows_mock.go -package=windows_mock
//

// Package windows_mock is a generated GoMock package.
package windows_mock
