// Code generated by MockGen. DO NOT EDIT.
// Source: ../aerospace-ipc/pkg/client/socket_test.go
//
// Generated by this command:
//
//	mockgen -source=../aerospace-ipc/pkg/client/socket_test.go -destination=internal/mocks/client/socket_test_mock.go -package=client_mock
//

// Package client_mock is a generated GoMock package.
package client_mock
