// Code generated by MockGen. DO NOT EDIT.
// Source: ../aerospace-ipc/pkg/aerospace/workspaces/workspaces_test.go
//
// Generated by this command:
//
//	mockgen -source=../aerospace-ipc/pkg/aerospace/workspaces/workspaces_test.go -destination=internal/mocks/workspaces/workspaces_test_mock.go -package=workspaces_mock
//

// Package workspaces_mock is a generated GoMock package.
package workspaces_mock
