// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/cristianoliveira/aerospace-ipc (interfaces: AeroSpaceClient)
//
// Generated by this command:
//
//	mockgen -package mock_aerospace github.com/cristianoliveira/aerospace-ipc AeroSpaceClient
//

// Package mock_aerospace is a generated GoMock package.
package mock_aerospace

import (
	reflect "reflect"

	"github.com/cristianoliveira/aerospace-ipc/pkg/aerospace/windows"
	"github.com/cristianoliveira/aerospace-ipc/pkg/aerospace/workspaces"
	client "github.com/cristianoliveira/aerospace-ipc/pkg/client"
	gomock "go.uber.org/mock/gomock"
)

// MockAeroSpaceClient is a mock of AeroSpaceClient interface.
type MockAeroSpaceClient struct {
	ctrl     *gomock.Controller
	recorder *MockAeroSpaceClientMockRecorder
	isgomock struct{}
}

// MockAeroSpaceClientMockRecorder is the mock recorder for MockAeroSpaceClient.
type MockAeroSpaceClientMockRecorder struct {
	mock *MockAeroSpaceClient
}

// NewMockAeroSpaceClient creates a new mock instance.
func NewMockAeroSpaceClient(ctrl *gomock.Controller) *MockAeroSpaceClient {
	mock := &MockAeroSpaceClient{ctrl: ctrl}
	mock.recorder = &MockAeroSpaceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAeroSpaceClient) EXPECT() *MockAeroSpaceClientMockRecorder {
	return m.recorder
}

// CloseConnection mocks base method.
func (m *MockAeroSpaceClient) CloseConnection() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseConnection")
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseConnection indicates an expected call of CloseConnection.
func (mr *MockAeroSpaceClientMockRecorder) CloseConnection() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseConnection", reflect.TypeOf((*MockAeroSpaceClient)(nil).CloseConnection))
}

// Connection mocks base method.
func (m *MockAeroSpaceClient) Connection() client.AeroSpaceConnection {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Connection")
	ret0, _ := ret[0].(client.AeroSpaceConnection)
	return ret0
}

// Connection indicates an expected call of Connection.
func (mr *MockAeroSpaceClientMockRecorder) Connection() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Connection", reflect.TypeOf((*MockAeroSpaceClient)(nil).Connection))
}

// GetAllWindows mocks base method.
func (m *MockAeroSpaceClient) GetAllWindows() ([]windows.Window, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllWindows")
	ret0, _ := ret[0].([]windows.Window)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllWindows indicates an expected call of GetAllWindows.
func (mr *MockAeroSpaceClientMockRecorder) GetAllWindows() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllWindows", reflect.TypeOf((*MockAeroSpaceClient)(nil).GetAllWindows))
}

// GetAllWindowsByWorkspace mocks base method.
func (m *MockAeroSpaceClient) GetAllWindowsByWorkspace(workspaceName string) ([]windows.Window, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllWindowsByWorkspace", workspaceName)
	ret0, _ := ret[0].([]windows.Window)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllWindowsByWorkspace indicates an expected call of GetAllWindowsByWorkspace.
func (mr *MockAeroSpaceClientMockRecorder) GetAllWindowsByWorkspace(workspaceName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllWindowsByWorkspace", reflect.TypeOf((*MockAeroSpaceClient)(nil).GetAllWindowsByWorkspace), workspaceName)
}

// GetFocusedWindow mocks base method.
func (m *MockAeroSpaceClient) GetFocusedWindow() (*windows.Window, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFocusedWindow")
	ret0, _ := ret[0].(*windows.Window)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFocusedWindow indicates an expected call of GetFocusedWindow.
func (mr *MockAeroSpaceClientMockRecorder) GetFocusedWindow() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFocusedWindow", reflect.TypeOf((*MockAeroSpaceClient)(nil).GetFocusedWindow))
}

// GetFocusedWorkspace mocks base method.
func (m *MockAeroSpaceClient) GetFocusedWorkspace() (*workspaces.Workspace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFocusedWorkspace")
	ret0, _ := ret[0].(*workspaces.Workspace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFocusedWorkspace indicates an expected call of GetFocusedWorkspace.
func (mr *MockAeroSpaceClientMockRecorder) GetFocusedWorkspace() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFocusedWorkspace", reflect.TypeOf((*MockAeroSpaceClient)(nil).GetFocusedWorkspace))
}

// MoveWindowToWorkspace mocks base method.
func (m *MockAeroSpaceClient) MoveWindowToWorkspace(windowID int, workspaceName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MoveWindowToWorkspace", windowID, workspaceName)
	ret0, _ := ret[0].(error)
	return ret0
}

// MoveWindowToWorkspace indicates an expected call of MoveWindowToWorkspace.
func (mr *MockAeroSpaceClientMockRecorder) MoveWindowToWorkspace(windowID, workspaceName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MoveWindowToWorkspace", reflect.TypeOf((*MockAeroSpaceClient)(nil).MoveWindowToWorkspace), windowID, workspaceName)
}

// SetFocusByWindowID mocks base method.
func (m *MockAeroSpaceClient) SetFocusByWindowID(windowID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetFocusByWindowID", windowID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetFocusByWindowID indicates an expected call of SetFocusByWindowID.
func (mr *MockAeroSpaceClientMockRecorder) SetFocusByWindowID(windowID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetFocusByWindowID", reflect.TypeOf((*MockAeroSpaceClient)(nil).SetFocusByWindowID), windowID)
}

// SetLayout mocks base method.
func (m *MockAeroSpaceClient) SetLayout(windowID int, layout string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetLayout", windowID, layout)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetLayout indicates an expected call of SetLayout.
func (mr *MockAeroSpaceClientMockRecorder) SetLayout(windowID, layout any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLayout", reflect.TypeOf((*MockAeroSpaceClient)(nil).SetLayout), windowID, layout)
}
