// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/cristianoliveira/other/aerospace-marks/pkgs/aerospacecli/configs.go
//
// Generated by this command:
//
//	mockgen -source=/Users/cristianoliveira/other/aerospace-marks/pkgs/aerospacecli/configs.go -destination=internal/mocks/aerospacecli/configs_mock.go -package=aerospacecli_mock
//

// Package aerospacecli_mock is a generated GoMock package.
package aerospacecli_mock
