// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/cristianoliveira/other/aerospace-marks/pkgs/aerospacecli/window_layout.go
//
// Generated by this command:
//
//	mockgen -source=/Users/cristianoliveira/other/aerospace-marks/pkgs/aerospacecli/window_layout.go -destination=internal/mocks/aerospacecli/window_layout_mock.go -package=aerospacecli_mock
//

// Package aerospacecli_mock is a generated GoMock package.
package aerospacecli_mock
