// Code generated by MockGen. DO NOT EDIT.
// Source: ../aerospace-ipc/pkg/aerospace/client_test.go
//
// Generated by this command:
//
//	mockgen -source=../aerospace-ipc/pkg/aerospace/client_test.go -destination=internal/mocks/aerospace/client_test_mock.go -package=aerospace_mock
//

// Package aerospace_mock is a generated GoMock package.
package aerospace_mock
