// Code generated by MockGen. DO NOT EDIT.
// Source: ../aerospace-ipc/pkg/aerospace/client.go
//
// Generated by this command:
//
//	mockgen -source=../aerospace-ipc/pkg/aerospace/client.go -destination=internal/mocks/aerospace/client_mock.go -package=aerospace_mock
//

// Package aerospace_mock is a generated GoMock package.
package aerospace_mock

import (
	reflect "reflect"

	windows "github.com/cristianoliveira/aerospace-ipc/pkg/aerospace/windows"
	workspaces "github.com/cristianoliveira/aerospace-ipc/pkg/aerospace/workspaces"
	client "github.com/cristianoliveira/aerospace-ipc/pkg/client"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// CloseConnection mocks base method.
func (m *MockClient) CloseConnection() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseConnection")
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseConnection indicates an expected call of CloseConnection.
func (mr *MockClientMockRecorder) CloseConnection() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseConnection", reflect.TypeOf((*MockClient)(nil).CloseConnection))
}

// Connection mocks base method.
func (m *MockClient) Connection() client.AeroSpaceConnection {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Connection")
	ret0, _ := ret[0].(client.AeroSpaceConnection)
	return ret0
}

// Connection indicates an expected call of Connection.
func (mr *MockClientMockRecorder) Connection() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Connection", reflect.TypeOf((*MockClient)(nil).Connection))
}

// Windows mocks base method.
func (m *MockClient) Windows() *windows.Service {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Windows")
	ret0, _ := ret[0].(*windows.Service)
	return ret0
}

// Windows indicates an expected call of Windows.
func (mr *MockClientMockRecorder) Windows() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Windows", reflect.TypeOf((*MockClient)(nil).Windows))
}

// Workspaces mocks base method.
func (m *MockClient) Workspaces() *workspaces.Service {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Workspaces")
	ret0, _ := ret[0].(*workspaces.Service)
	return ret0
}

// Workspaces indicates an expected call of Workspaces.
func (mr *MockClientMockRecorder) Workspaces() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Workspaces", reflect.TypeOf((*MockClient)(nil).Workspaces))
}
