// Code generated by MockGen. DO NOT EDIT.
// Source: ../aerospace-ipc/pkg/aerospace/root.go
//
// Generated by this command:
//
//	mockgen -source=../aerospace-ipc/pkg/aerospace/root.go -destination=internal/mocks/aerospace/root_mock.go -package=aerospace_mock
//

// Package aerospace_mock is a generated GoMock package.
package aerospace_mock
